version: "3.9"

services:
  web:
    build:
      context: .
      args:
        DEVELOPMENT: 1
      target: dev
    command: tail -f /dev/null
    volumes:
      - ./:/home/flask/app/
    ports:
      - 8000:8000
    env_file:
      - env/.dev.env
    environment:
      - FLASK_CONFIGURATION=development
      - FLASK_ENV=development
      - NODE_ENV=development
